# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=alpine

[Content]
VolatilePackages=
        dbus
        dbus-libs
        systemd
        systemd-boot
        systemd-container
        systemd-journal-remote
        systemd-libs
        systemd-tests
        systemd-ukify

Packages=
        bind-tools
        bpftool
        btrfs-progs
        cryptsetup
        erofs-utils
        f2fs-tools
        gnutls-utils
        iproute2
        iputils
        knot
        libcap-ng-utils
        libcap-utils
        libqrencode-tools
        linux-pam
        linux-stable
        lvm2-dmeventd
        man-db
        multipath-tools
        net-tools
        nmap-ncat
        open-iscsi
        openssh-client
        openssh-server
        openssl
        perf
        polkit
        procps-ng
        py3-elftools
        py3-pexpect
        py3-pytest
        py3-zstd
        quota-tools
        sbsigntool
        scsi-tgt
        sfdisk
        shadow
        softhsm
        squashfs-tools
        stress-ng
        tpm2-tools
        tpm2-tss-esys
        tpm2-tss-rc
        tpm2-tss-tcti-device
        tzdata
        util-linux-misc
        vim-common
