# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=alpine

[Include]
Include=%D/mkosi/mkosi.conf.d/alpine/mkosi.conf.d/split-usr.conf

[Content]
VolatilePackages=
        dbus
        dbus-libs
        systemd
        systemd-libs

Packages=
        util-linux-misc

        btrfs-progs
        dosfstools
        e2fsprogs
        xfsprogs
